# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSdemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOSdemo

  target 'iOSdemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSdemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  pod 'Cordova'
  #相机插件
  pod 'cordova-plugin-camera'
  #wkwebview插件
  pod 'cordova-plugin-wkwebview-engine'

end
